<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container21fCCoi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container21fCCoi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container21fCCoi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container21fCCoi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container21fCCoi\App_KernelDevDebugContainer([
    'container.build_hash' => '21fCCoi',
    'container.build_id' => 'd846aa87',
    'container.build_time' => 1768375719,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container21fCCoi');
